<?php

namespace Tests\Mocks;

/**
 * In-process stub for the AI provider.
 *
 * Returns a deterministic Markdown fixture (heading level 1 + body of
 * >= 100 chars) so endpoint tests and Markdown validation can be
 * exercised without a real provider. Lives under tests/Mocks/ on
 * purpose — the real `App\Services\Ai\*` classes will land later and
 * this stub stays out of the production autoloader.
 */
class MockAiProvider implements AiProviderInterface
{
    /**
     * Configurable Markdown fixture. Defaults to a valid PLANNING.md-
     * style document with one `#` heading and a 100+ char body.
     */
    public string $fixtureMarkdown;

    /**
     * Captured calls so tests can assert what the prompt looked like.
     *
     * @var array<int, array{messages: array, options: array}>
     */
    public array $calls = [];

    /**
     * Token estimate per input character. Default heuristic
     * `chars / 4` mirrors common OpenAI approximations.
     */
    public int $tokensPerChar = 4;

    public function __construct(?string $fixtureMarkdown = null)
    {
        $this->fixtureMarkdown = $fixtureMarkdown ?? self::defaultFixture();
    }

    /**
     * Default Markdown fixture: valid H1 + 100+ char body.
     */
    public static function defaultFixture(): string
    {
        $body = "This is a fixture document generated by the MockAiProvider for testing purposes. "
            . "It contains enough content to satisfy the >= 100 character body requirement "
            . "set by the MarkdownValidator and to be parsed by downstream consumers.";

        return "# PLANNING\n\n{$body}\n";
    }

    /**
     * @param array<int, array{role: string, content: string}> $messages
     * @param array<string, mixed> $options
     */
    public function chat(array $messages, array $options = []): AiResponse
    {
        $this->calls[] = [
            'messages' => $messages,
            'options' => $options,
        ];

        $promptChars = 0;
        foreach ($messages as $message) {
            $promptChars += strlen((string) ($message['content'] ?? ''));
        }

        $tokensIn = (int) ceil($promptChars / $this->tokensPerChar);
        $tokensOut = (int) ceil(strlen($this->fixtureMarkdown) / $this->tokensPerChar);

        return new AiResponse(
            content: $this->fixtureMarkdown,
            tokens_in: $tokensIn,
            tokens_out: $tokensOut,
            latency_ms: 0,
            provider: 'mock'
        );
    }

    public function estimateTokens(string $prompt): int
    {
        return (int) ceil(strlen($prompt) / $this->tokensPerChar);
    }

    /**
     * Reset the call log between assertions.
     */
    public function reset(): void
    {
        $this->calls = [];
    }
}